import {
  HardHat,
  Truck,
  Factory,
  Stethoscope,
  UtensilsCrossed,
  Tractor,
  Server,
  Zap,
  Percent,
  SlidersHorizontal,
  MapPin,
  UserCheck,
  FileText,
  BadgeCheck,
  Search,
  TrendingUp,
  Landmark,
  Plane,
  Pickaxe,
  Trees,
  FileSignature,
  Repeat,
  Handshake,
  Gavel,
  Globe,
  Banknote,
  type LucideIcon,
  Package,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  HardHat,
  Truck,
  Factory,
  Stethoscope,
  UtensilsCrossed,
  Tractor,
  Server,
  Zap,
  Percent,
  SlidersHorizontal,
  MapPin,
  UserCheck,
  FileText,
  BadgeCheck,
  Search,
  TrendingUp,
  Landmark,
  Plane,
  Pickaxe,
  Trees,
  FileSignature,
  Repeat,
  Handshake,
  Gavel,
  Globe,
  Banknote,
};

export function DynamicIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = (name && map[name]) || Package;
  return <Icon className={className} />;
}
